//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VEIPv2._0.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VEIPv2._0.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Complete Flag
        ///Command Error Flag
        ///Command Ready Flag
        ///Result Ready Flag
        ///Result OR Flag
        ///Reserved
        ///Reserved
        ///Reserved
        ///READY1
        ///READY2
        ///READY3
        ///READY4
        ///Reserved
        ///Reserved
        ///Reserved
        ///Reserved
        ///ACK1
        ///ACK2
        ///ACK3
        ///ACK4
        ///Reserved
        ///Reserved
        ///Reserved
        ///Reserved
        ///BUSY
        ///ERROR
        ///Reserved
        ///RUN
        ///Reserved
        ///Reserved
        ///Reserved
        ///Reserved
        ///Tool Judge Value0
        ///Tool Judge Value1
        ///Tool Judge Value2
        ///Tool Judge Value3
        ///Tool Judge Value4
        ///Tool Judge Value5
        ///Tool Judge Value6
        ///Tool Judge Value7
        ///Tool Judge Value8
        ///Tool Judg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VEIP2_Tags {
            get {
                return ResourceManager.GetString("VEIP2_Tags", resourceCulture);
            }
        }
    }
}
